export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_TEACHER_REQUEST = "LOGIN_TEACHER_REQUEST";
export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS";
export const LOGIN_TEACHER_FAILURE = "LOGIN_TEACHER_FAILURE";
export const LOGOUT_TEACHER = "LOGOUT_TEACHER";
